version: '3.8'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  localstack:
    image: localstack/localstack:latest
    environment:
      - DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
      - SERVICES=s3,lambda,logs
    ports:
      - '4566-4583:4566-4583'

volumes:
  db:
    driver: local